name: resign

on:
  workflow_dispatch:
    inputs:
      ZIP_URL:    
        description: 'URL of (splloader)+uboot+sml+trustos+(teecfg)+vbmeta+boot+recovery (all end with .bin)'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main
        path: main

    - name: patch
      run: |
        sudo apt update
        sudo apt -y install build-essential python openssl curl wget
        wget https://bootstrap.pypa.io/pip/2.7/get-pip.py && sudo python2.7 get-pip.py
        pip2 install pycryptodome
        curl -o original.zip -L "${{ github.event.inputs.ZIP_URL }}"
        curl -o avbtool.tgz -L "https://android.googlesource.com/platform/external/avb/+archive/refs/heads/pie-release.tar.gz"
        curl -o magisk.apk -L $(curl -s https://api.github.com/repos/topjohnwu/Magisk/releases/latest | grep -Po '(?<=download_url\"\: \").*Magisk.*apk')
        wget https://raw.githubusercontent.com/magojohnji/magiskboot-linux/main/x86_64/magiskboot
        chmod +x magiskboot
        chmod +x main/*.sh
        mkdir work
        busybox unzip -oq original.zip -d work
        mkdir boot
        mkdir recovery
        mkdir -p vbmeta/keys
        tar xzvf avbtool.tgz -C vbmeta/
        mv work/boot* boot/boot.img
        mv work/recovery* recovery/recovery.img
        mv work/vbmeta* vbmeta/keys/vbmeta.img
        mkdir boot/zzz
        busybox unzip -oq magisk.apk -d boot/zzz
        mv main/boot_patch_9.sh boot/
        mv main/boot_patch_10.sh boot/
        mv main/sign.sh ./
        git clone https://github.com/TomKing062/vendor_sprd_proprietories-source_packimage.git
        cp -a vendor_sprd_proprietories-source_packimage/sign_image/v2/prebuilt/* work/
        cp -a vendor_sprd_proprietories-source_packimage/sign_image/config-unisoc work/
        cp vendor_sprd_proprietories-source_packimage/sign_image/v2/sign_image_v2.sh work/
        gcc -o work/get-raw-image vendor_sprd_proprietories-source_packimage/sign_image/get-raw-image.c
        chmod +x work/*
        cd vendor_sprd_proprietories-source_packimage/sign_vbmeta
        make
        chmod +x generate_sign_script_for_vbmeta
        cp generate_sign_script_for_vbmeta ../../vbmeta/keys/
        cd ../../vbmeta/keys/
        ./generate_sign_script_for_vbmeta vbmeta.img
        mv sign_vbmeta.sh ../
        mv padding.py ../
        cd ../..
        cp vendor_sprd_proprietories-source_packimage/sign_image/config-unisoc/rsa4096_boot.pem vbmeta/
        cp -f vendor_sprd_proprietories-source_packimage/sign_image/config-unisoc/rsa4096_boot_pub.bin vbmeta/keys/
        cp vendor_sprd_proprietories-source_packimage/sign_image/config-unisoc/rsa4096_recovery.pem vbmeta/
        cp -f vendor_sprd_proprietories-source_packimage/sign_image/config-unisoc/rsa4096_recovery_pub.bin vbmeta/keys/
        cp vendor_sprd_proprietories-source_packimage/sign_image/config-unisoc/rsa4096_vbmeta.pem vbmeta/
        chmod +x vbmeta/*
        sudo rm -rf /usr/bin/python
        sudo ln -s /usr/bin/python2 /usr/bin/python
        cd vbmeta
        ./sign_vbmeta.sh
        python padding.py
        cd ..
        ./sign.sh
        cd work
        ./sign_image_v2.sh
        cd ..
        mkdir output
        cp work/*-sign.bin output/
        cp boot/patched.img output/boot.img
        cp recovery/recovery.img output/recovery.img
        cp vbmeta/vbmeta-sign-custom.img output/vbmeta.img
        zip -r -v resigned.zip output

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: | 
          resigned.zip
        name: ${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: |
          URL: ${{ github.event.inputs.ZIP_URL }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
